// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qcmpHANVPtApEXtA2usI8BhwyrBLFD8',
    appId: '1:51740691666:web:be0caf00f2955a0e54710b',
    messagingSenderId: '51740691666',
    projectId: 'vuna-pay-2',
    authDomain: 'vuna-pay-2.firebaseapp.com',
    storageBucket: 'vuna-pay-2.firebasestorage.app',
    measurementId: 'G-KVDSQ8KBDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClk756lUPDZsJoOoNRwG4EcS5Sh1Q3j3k',
    appId: '1:51740691666:android:dd64a6a7e100297b54710b',
    messagingSenderId: '51740691666',
    projectId: 'vuna-pay-2',
    storageBucket: 'vuna-pay-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxR92zT0GHYEKG-0_Et5NcaptbhlduAys',
    appId: '1:51740691666:ios:24d04d04ecd831a754710b',
    messagingSenderId: '51740691666',
    projectId: 'vuna-pay-2',
    storageBucket: 'vuna-pay-2.firebasestorage.app',
    iosBundleId: 'com.vunapay.demo.vunapayDemo',
  );
}
